### ISSUE TITLE
Format of converted RGBA is not optimal

### ISSUE THREAD

**Issue by ghost** [DakshMiglani/VSCode-Hex-To-RGBA#1]
Hey there,

thank you for creating this very useful little extension. Just downloaded it and it helped me a lot already!

When I convert a hex-color to rgba the format of the rgba looks like this: rgba(128, 255 ,255, 0.05)
The second and third value are currently formatted without proper spacing. 

My suggestion/wish is that you would change the format to this: rgba(128, 255, 255, 0.05)

It's just something that would be the icing on the cake so to speak. Making the extension even better!

Greetings
julian

**Comment by sudodaksh** [comment]
Sure, I'll if I am able to get some time this weekend.
