### ISSUE TITLE
does not support hex alpha channel

### ISSUE THREAD

**Issue by mscottnelson** [DakshMiglani/VSCode-Hex-To-RGBA#2]
I have a use case where a designer gave me values in HEX + Alpha %. This tool is great for this, since it can take HEX_%% and convert to rgba. But, in playing with it, I noticed that it does not support alpha hex channels OOTB. For example, #d9e0e7a6 (transparent grey) should become rgba(217,224,231,0.65), but instead it becomes rgba(221, 153, 238, 1) (opaque purple-pink).

**Comment by sudodaksh** [comment]
you're right, I just verified this. I'll work on it.

**Comment by sudodaksh** [comment]
fixed in commit: #e4bb5317f187ba50ed31cf3d0a63e9f8b40101e9 and published in release 0.0.5
