### ISSUE TITLE
add multi cursor support

### ISSUE THREAD

**Issue by karladler** [DakshMiglani/VSCode-Hex-To-RGBA#7]
This is already an awesome tool, but it would be even better if it could convert ALL selected colors at once.

**Comment by sudodaksh** [comment]
I'm not sure how to implement it, any guides?

**Comment by karladler** [comment]
mh not sure, I never developed a VS-Code plugin and as it looks like it should be already applied to the array of selections, maybe you can debug why it doesn't by logging out the selected from here: https://github.com/DakshMiglani/VSCode-Hex-To-RGBA/blob/master/src/extension.ts#L22

**Comment by sudodaksh** [comment]
Let me see if I can implement it this weekend. Thank you 👍

**Comment by sudodaksh** [comment]
I just tried it out, it already works on multiple selections! Let me know where you are having trouble?

**Comment by karladler** [comment]
Weird, last time I tried it didn't worked. Works perfect now. Thank you!

**Comment by sudodaksh** [comment]
Lovely. thank you for your time :)
